### ISSUE TITLE
Pass through stdin to command

### ISSUE THREAD

**Issue by toshi0383** [yonaskolb/Mint#38] opened 2017-12-18 16:29 UTC
Mint should pass stdin to executing command. (just as `cmdshelf` is doing)
```
Mint $ cat > ~/.cmdshelf/remote/toshi0383/hello.sh
cat # creating hello.sh with content "cat"
Mint $ chmod +x ~/.cmdshelf/remote/toshi0383/hello.sh
Mint $ cmdshelf run hello.sh
hey # user input
hey # printed by `cat` command
Mint $ ./.build/x86_64-apple-macosx10.10/debug/mint run toshi0383/cmdshelf "cmdshelf run hello.sh"
🌱  Finding latest version of cmdshelf
🌱  Using cmdshelf "0.8.0"
🌱  cmdshelf "0.8.0" already installed
🌱  Running cmdshelf "0.8.0"...
# stdin is disabled
Mint $
```

**Comment by yonaskolb** [comment] 2017-12-18 16:31
Duplicate of #37

**Closed by yonaskolb** 2017-12-18 16:31 UTC

**Comment by toshi0383** [comment] 2017-12-18 16:32
Oh sorry I didn't notice🤕

**Comment by yonaskolb** [comment] 2017-12-18 16:33
Do you have any advice for the maintainer of SwiftShell regarding the linked issue?

**Comment by toshi0383** [comment] 2017-12-18 17:11
I've left a comment just for information👌
